model:
  target: core.module.DDPM.DDPM.DDPM
  params:
    unet_config:
      target: core.module.unet.unet.UNetModel
      params:
        in_channels: 3
        model_channels: 224
        out_channels: 3
        num_res_blocks: 2
        attention_resolutions: [8,4,2]
        dropout: 0
        channel_mult: [1, 2, 3, 4]
        conv_resample: True
        dims: 2
        num_classes: Null
        use_checkpoint: False
        num_heads: 1
        num_heads_upsample: -1
        use_scale_shift_norm: False

